name: CI - Jest tests

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (clean)
        run: npm ci

      - name: Run tests
        env:
          CI: true
        run: npm test
